### ISSUE TITLE
Errore export risultati

### ISSUE THREAD

**Issue by matteobalsemin** [emmenove/osda#1]
Dopo aver completato con successo l'elaborazione della lista (menù Process>Check), viene visualizzato un errore qualora si decida di esportare i risultati (menù Export>Export excel results). In allegato screenshot dell'errore.

Qualora invece si provi ad utilizzare la funzione "export raw results", la procedura viene completata con successo (vedi screenshot allegato), ma il file di output è vuoto (vedi allegato).

**Errore export excel:**
![Errore_export_excel](https://github.com/user-attachments/assets/744e2a55-3cbe-42fb-a9cc-57b2d5978f61)

**Conferma export raw results:**
![Conferma_export_raw](https://github.com/user-attachments/assets/a6b2049e-4256-474b-a91c-5f143d7631f7)
[raw-results.json](https://github.com/user-attachments/files/16763932/raw-results.json)

**Comment by emmenove** [comment]
Ciao,
l'errore è causato dalla mancanza di risultati. Lo noto dalla icona orologio a fianco del nome azienda in lista, che significa appunto che non esistono risultati per la riga

Correggerò l'anomalia indicando la mancanza di dati, ma al momento vorrei capire come mai non hai risultati. Mi potresti passare la schermata della configurazione ed il file relativo? (tasto window+R e digita %AppData%\osda\config.json nella casella di testo)

Di seguito cosa dovresti vedere in tabella dopo il process:
![image](https://github.com/user-attachments/assets/8b81e238-43ea-4e7c-83ac-ac1066b40240)

**Comment by matteobalsemin** [comment]
Ciao Francesco, il file di configurazione contiene questo setup:
{
  "apiKey": "80551709570ae74b128c4ac75a2e2057",
  "collezione": "sanctions",
  "nominativo": "Ragione sociale",
  "giurisdizione": "",
  "indirizzo": "",
  "limit": "5",
  "threshold": "0.7",
  "cutoff": "0.5"
}

![immagine](https://github.com/user-attachments/assets/8a839da8-a72f-4d63-a08e-11f55180aaf9)

**Comment by matteobalsemin** [comment]
Questo il file con la lista delle società

[Export 22_08_2024 16_26_VR.xlsx](https://github.com/user-attachments/files/16786624/Export.22_08_2024.16_26_VR.xlsx)

**Comment by emmenove** [comment]
Ok, visto il problema. Ho fatto casino con la chiamata....
Intanto aggiungi in configurazione, nel campo giurisdizione il valore 'Paese' (è l'indicazione del campo da cui prendere il paese nel file)
Con quello dovrebbe andare.

Domani cerco di correggere il problema 
Ciao

**Comment by matteobalsemin** [comment]
ciao Francesco, ti confermo che con il valore "Paese" funziona. Visto che questo non è un campo obbligatorio (e, in molti casi, avrò solo la "ragione sociale" senza il "paese"), puoi prevedere a codice che se il campo Paese è presente nella lista importata allora viene passato per l'elaborazione, altrimenti viene utilizzato solo la ragione sociale?

**Comment by matteobalsemin** [comment]
O meglio ancora, semplifichiamo le cose: se nella configurazione dell'applicativo viene popolato il campo "giurisdizione", allora utilizza il valore nella chiamata API per tutte le entry della lista. Altrimenti utilizzi solo l'info sulla ragione sociale. Sarò io ad attivare/disattivare manualmente il campo dalla configurazione per tutte le entry della lista. Fammi sapere se può aiutarti

**Comment by emmenove** [comment]
Ciao!
Ho implementato le logiche:
1) Se definisci il campo viene utilizzato nella chiamata, a patto che sia valorizzato nel file excel
2) Se non lo definisci viene escluso per tutti (ma non si arrabbia)

Ho inoltre rilasciato le seguenti modifiche
- collegati i campi limit/threshold/cutoff che prima non incidevano sulla chiamata
- azzeramento dei risultati al check (prima rimaneva valorizzato il precedente)
- aggiunto il parametro di algoritmo in modo che tu possa giocare meglio con i test
- modificate icone per mettere in risalto quello con dei topics nei risultati

Per il significato dei valori di configurazione verifica la pagina di help:
https://api.opensanctions.org/#tag/Matching/operation/match_match__dataset__post

Trovi la nuova release all'indirizzo:
https://github.com/emmenove/osda/releases/download/untagged-d7043cbc3403d81fa409/osda-0.1.2.Setup.exe

PS: chiudo questa issue e procediamo su nuove

**Comment by matteobalsemin** [comment]
Ciao Francesco, sei un fenomeno, volevo proprio chiederti di poter giocare con il parametro dell’algoritmo perché quello attuale non mi convince del tutto 😉

Nei prossimi giorni ci gioco un po’ e poi ti dico. Mi sto sentendo con alcuni smanettoni nella loro piattaforma Slack per farmi suggerire il setup migliore per la tipologia di screening che devo fare. Ti scrivo se dovesse servire qualche altro parametro nella chiamata

Ciao e buon weekend!
